### ISSUE TITLE
Compatibilité avec Piper dans Home Assistant

### ISSUE THREAD

**Issue by Charly314159** [TazzerMAN/piper-voice-glados-fr#1]
Bonjour TazzerMan,

et merci pour ce modèle, c'est une super idée! je rêve d'en faire la voix pour mon Home assitant!

Mais j'ai quelque problème de compatibilité avec l'intégration piper que je ne rencontre pas avec  d'autres modèles. La voix est bien détecté par piper mais lorsque je génère une phrase j'ai l'erreur ci-dessous.

Est-ce qu'il y a quelque chose d'évident que je ne vois pas?

Merci d'avance!

`ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='wyoming event handler' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.11/dist-packages/wyoming/server.py:31> exception=VoiceNotFoundError('GlaDOS')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 41, in run
    if not (await self.handle_event(event)):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 53, in handle_event
    raise err
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 48, in handle_event
    return await self._handle_event(event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 83, in _handle_event
    piper_proc = await self.process_manager.get_process(voice_name=voice_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/process.py", line 114, in get_process
    ensure_voice_exists(
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/download.py", line 77, in ensure_voice_exists
    find_voice(name, data_dirs)
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/download.py", line 183, in find_voice
    raise VoiceNotFoundError(name)
wyoming_piper.download.VoiceNotFoundError: GlaDOS`

**Comment by Charly314159** [comment]
Problème résolu!

j'ai édité le .json pour que le nom corresponde au nom des fichiers.

Merci!

**Comment by TazzerMAN** [comment]
Bonjour @Charly314159 ,

Désolé pour le délai de réponse. 
Ravi d'apprendre que tout fonctionne maintenant. Bon amusement avec ton projet et bonne année 2025 !
